#!/usr/bin/env bash
# 12-tell_the_story_of_passwd
# Reads /etc/passwd and prints a descriptive line for each user

while IFS=: read -r username password user_id group_id user_info home_dir shell
do
    echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

