#!/usr/bin/env bash
# Tell the story of each user in /etc/passwd

while IFS=: read -r user pass uid gid _ home shell; do
 echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $user"
done < /etc/passwd
