#!/usr/bin/env bash
# Displays numbers 1 to 20 with superstition messages
i=1
while [ $i -le 20 ]; do
  if [ $i -eq 4 ]; then
    echo "$i: bad luck"
  elif [ $i -eq 9 ]; then
    echo "$i: bad luck from China"
  elif [ $i -eq 17 ]; then
    echo "$i: bad luck from Italy"
  else
    echo "$i"
  fi
  ((i++))
done

