#!/usr/bin/env bash
# Displays numbers 1 to 20 with superstition messages using case
i=1
while [ $i -le 20 ]; do
  case $i in
    4)
      echo "$i: bad luck from China"
      ;;
    9)
      echo "$i: bad luck from Japan"
      ;;
    17)
      echo "$i: bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  ((i++))
done

